# generated by datamodel-codegen:
#   filename:  defs/attributes/reqif.json
#   timestamp: 2025-12-09T12:53:52+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field, RootModel

from ...types.types import DateAttribute


class ReqifAttributeDefinitions(RootModel[Any]):
    root: Any = Field(..., title='ReqIF Attribute Definitions')
    """
    JSON Schema for the ReqIf attributes
    """


class LastChange(DateAttribute):
    longName: Literal['LAST-CHANGE'] = 'LAST-CHANGE'
