# generated by datamodel-codegen:
#   filename:  defs/requirement_doors.json
#   timestamp: 2025-12-10T22:32:46+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel

from .types import types
from .types.types import EnumerationAttribute, StringAttribute


class ReqifDoorsRequirementMappingSchema(RootModel[Any]):
    root: Any = Field(..., title='ReqIF DOORS Requirement Mapping Schema')
    """
    JSON Schema with the Requirement fields
    """


class IEPUID(StringAttribute):
    longName: Literal['IE PUID'] = 'IE PUID'


class IEObjectType(EnumerationAttribute):
    longName: Literal['IE Object Type'] = 'IE Object Type'


class Requirement(BaseModel):
    IE_PUID: IEPUID = Field(..., alias='IE PUID')
    IE_Object_Type: IEObjectType = Field(..., alias='IE Object Type')


class AdditionalProperties(RootModel[types.AnyAttributeValue]):
    root: types.AnyAttributeValue
