# generated by datamodel-codegen:
#   filename:  defs/requirement.json
#   timestamp: 2025-12-10T22:32:46+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field, RootModel

from .attributes import reqif
from .attributes.reqif import ReqIF


class ReqifRequirementMappingSchema(RootModel[Any]):
    root: Any = Field(..., title='ReqIF Requirement Mapping Schema')
    """
    JSON Schema with the Requirement fields
    """


class Requirement(BaseModel):
    lastChange: Optional[reqif.LastChange] = None
    ReqIF_AssociatedFiles: Optional[ReqIF.AssociatedFiles] = Field(
        None, alias='ReqIF.AssociatedFiles'
    )
    ReqIF_Category: Optional[ReqIF.Category] = Field(None, alias='ReqIF.Category')
    ReqIF_ChangeDescription: Optional[ReqIF.ChangeDescription] = Field(
        None, alias='ReqIF.ChangeDescription'
    )
    ReqIF_ChapterName: Optional[ReqIF.ChapterName] = Field(
        None, alias='ReqIF.ChapterName'
    )
    ReqIF_ChapterNumber: Optional[ReqIF.ChapterNumber] = Field(
        None, alias='ReqIF.ChapterNumber'
    )
    ReqIF_Description: Optional[ReqIF.Description] = Field(
        None, alias='ReqIF.Description'
    )
    ReqIF_FitCriteria: Optional[ReqIF.FitCriteria] = Field(
        None, alias='ReqIF.FitCriteria'
    )
    ReqIF_ForeignCreatedBy: Optional[ReqIF.ForeignCreatedBy] = Field(
        None, alias='ReqIF.ForeignCreatedBy'
    )
    ReqIF_ForeignCreatedOn: Optional[ReqIF.ForeignCreatedOn] = Field(
        None, alias='ReqIF.ForeignCreatedOn'
    )
    ReqIF_ForeignCreatedThru: Optional[ReqIF.ForeignCreatedThru] = Field(
        None, alias='ReqIF.ForeignCreatedThru'
    )
    ReqIF_ForeignDeleted: Optional[ReqIF.ForeignDeleted] = Field(
        None, alias='ReqIF.ForeignDeleted'
    )
    ReqIF_ForeignID: Optional[ReqIF.ForeignID] = Field(None, alias='ReqIF.ForeignID')
    ReqIF_ForeignModifiedBy: Optional[ReqIF.ForeignModifiedBy] = Field(
        None, alias='ReqIF.ForeignModifiedBy'
    )
    ReqIF_ForeignRevision: Optional[ReqIF.ForeignRevision] = Field(
        None, alias='ReqIF.ForeignRevision'
    )
    ReqIF_Name: ReqIF.Name = Field(..., alias='ReqIF.Name')
    ReqIF_Text: ReqIF.Text = Field(..., alias='ReqIF.Text')
