# generated by datamodel-codegen:
#   filename:  defs/specification_doors.json
#   timestamp: 2025-12-10T22:32:46+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel

from .types.types import StringAttribute


class ReqifSpecificationMappingSchema(RootModel[Any]):
    root: Any = Field(..., title='ReqIF Specification Mapping Schema')
    """
    JSON Schema with the default Specification fields
    """


class IEPUID(StringAttribute):
    longName: Literal['IE PUID'] = 'IE PUID'
    maxLength: Literal[50] = 50
    type: Literal['UID'] = 'UID'


class Specification(BaseModel):
    """
    Requirements specification/document container
    """

    IE_PUID: IEPUID = Field(..., alias='IE PUID')
