# generated by datamodel-codegen:
#   filename:  defs/specification.json
#   timestamp: 2025-12-09T12:53:52+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field, RootModel

from .attributes import reqif
from .attributes.reqif import ReqIF


class ReqifDoorsSpecificationMappingSchema(RootModel[Any]):
    root: Any = Field(..., title='ReqIF DOORS Specification Mapping Schema')
    """
    JSON Schema with the default Specification fields
    """


class Specification(BaseModel):
    """
    Requirements specification/document container
    """

    lastChange: Optional[reqif.LastChange] = None
    ReqIF_ChangeDescription: Optional[ReqIF.ChangeDescription] = Field(
        None, alias='ReqIF.ChangeDescription'
    )
    ReqIF_Description: ReqIF.Description = Field(..., alias='ReqIF.Description')
    ReqIF_ForeignBaseline: Optional[ReqIF.ForeignBaseline] = Field(
        None, alias='ReqIF.ForeignBaseline'
    )
    ReqIF_ForeignCreatedBy: Optional[ReqIF.ForeignCreatedBy] = Field(
        None, alias='ReqIF.ForeignCreatedBy'
    )
    ReqIF_ForeignCreatedOn: Optional[ReqIF.ForeignCreatedOn] = Field(
        None, alias='ReqIF.ForeignCreatedOn'
    )
    ReqIF_ForeignID: ReqIF.ForeignID = Field(..., alias='ReqIF.ForeignID')
    ReqIF_ForeignRevision: Optional[ReqIF.ForeignRevision] = Field(
        None, alias='ReqIF.ForeignRevision'
    )
    ReqIF_ForeignModifiedBy: Optional[ReqIF.ForeignModifiedBy] = Field(
        None, alias='ReqIF.ForeignModifiedBy'
    )
    ReqIF_ForeignState: Optional[ReqIF.ForeignState] = Field(
        None, alias='ReqIF.ForeignState'
    )
    ReqIF_Name: ReqIF.Name = Field(..., alias='ReqIF.Name')
    ReqIF_Prefix: Optional[ReqIF.Prefix] = Field(None, alias='ReqIF.Prefix')
    ReqIF_Project: Optional[ReqIF.Project] = Field(None, alias='ReqIF.Project')
