# generated by datamodel-codegen:
#   filename:  defs/types/defaults.json
#   timestamp: 2025-12-11T15:53:13+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field, RootModel


class ReqifAttributeTypeDefinitions(RootModel[Any]):
    root: Any = Field(..., title='ReqIF Attribute Type Definitions')
    """
    Reusable attribute type definitions based on prostep ivip ReqIF Implementation Guide v1.8
    """


class Selector(RootModel[str]):
    root: str
    """
    JSONPath pointer to the element from the parent node
    """


class Config(BaseModel):
    tool: str
    """
    Tool name to reflect in the specification
    """
    toolVersion: str
    """
    Tool version to reflect in the specification
    """
    repository: str
    """
    Repository identifier to match requirement groups against each other
    """


class FieldDefaultAttrs(BaseModel):
    selector: str
    """
    JSONPath pointer to the element from the parent node
    """
    literal: Optional[str] = None
    """
    Literal value for missing selector
    """
    longName: str
    """
    Long name for the attributes to reflect in ReqIf specification
    """
    attributeType: str
    """
    Attribute type in the specifications
    """
    type: Optional[str] = None
    """
    Datatype Name to be used in specification as {attributeType_type}
    """
