# generated by datamodel-codegen:
#   filename:  defs/relation.json
#   timestamp: 2025-12-11T15:53:13+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field, RootModel

from .attributes import reqif
from .attributes.reqif import ReqIF


class ReqifRelationMappingSchema(RootModel[Any]):
    root: Any = Field(..., title='ReqIF Relation Mapping Schema')
    """
    JSON Schema with the default Relation fields
    """


class Relation(BaseModel):
    """
    Relationship/link between requirements
    """

    lastChange: Optional[reqif.LastChange] = None
    ReqIF_Description: Optional[ReqIF.Description] = Field(
        None, alias='ReqIF.Description'
    )
    ReqIF_ForeignCreatedBy: Optional[ReqIF.ForeignCreatedBy] = Field(
        None, alias='ReqIF.ForeignCreatedBy'
    )
    ReqIF_ForeignCreatedOn: Optional[ReqIF.ForeignCreatedOn] = Field(
        None, alias='ReqIF.ForeignCreatedOn'
    )
    ReqIF_ForeignID: Optional[ReqIF.ForeignID] = Field(None, alias='ReqIF.ForeignID')
    ReqIF_ForeignModifiedBy: Optional[ReqIF.ForeignModifiedBy] = Field(
        None, alias='ReqIF.ForeignModifiedBy'
    )
    ReqIF_Name: Optional[ReqIF.Name] = Field(None, alias='ReqIF.Name')
