# generated by datamodel-codegen:
#   filename:  defs/types/types.json
#   timestamp: 2025-12-09T12:53:52+00:00

from __future__ import annotations

from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint

from .defaults import FieldDefaultAttrs


class ReqifAttributeTypeDefinitions(RootModel[Any]):
    root: Any = Field(..., title='ReqIF Attribute Type Definitions')
    """
    Reusable attribute type definitions based on prostep ivip ReqIF Implementation Guide v1.8
    """


class BooleanAttribute(FieldDefaultAttrs):
    """
    AttributeDefinitionBoolean / AttributeValueBoolean - for true/false values
    """

    attributeType: Literal['BOOLEAN'] = 'BOOLEAN'


class DateAttribute(FieldDefaultAttrs):
    """
    AttributeDefinitionDate / AttributeValueDate - for temporal values
    """

    attributeType: Literal['DATE'] = 'DATE'


class EnumerationAttributeValue(BaseModel):
    """
    AttributeDefinitionEnumerationValue - for predefined choices
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    key: int
    value: str
    content: str


class EnumerationAttribute(FieldDefaultAttrs):
    """
    AttributeDefinitionEnumeration / AttributeValueEnumeration - for predefined choices
    """

    attributeType: Literal['ENUMERATION']
    values: list[EnumerationAttributeValue] = Field(..., min_length=1)


class IntegerAttribute(FieldDefaultAttrs):
    """
    AttributeDefinitionInteger / AttributeValueInteger - for integer values
    """

    attributeType: Literal['INTEGER'] = 'INTEGER'
    min: Optional[Any] = None
    max: Optional[int] = None


class RealAttribute(FieldDefaultAttrs):
    """
    AttributeDefinitionReal / AttributeValueReal - for numeric values with decimals
    """

    attributeType: Literal['REAL'] = 'REAL'
    accuracy: Optional[Any] = None
    """
    Number of decimal places
    """
    min: Optional[int] = None
    max: Optional[int] = None


class StringAttribute(FieldDefaultAttrs):
    """
    AttributeDefinitionString / AttributeValueString - for text values
    """

    attributeType: Literal['STRING'] = 'STRING'
    maxLength: Optional[conint(ge=0)] = None


class XHTMLAttribute(FieldDefaultAttrs):
    """
    AttributeDefinitionXHTML / AttributeValueXHTML - for formatted content
    """

    attributeType: Literal['XHTML'] = 'XHTML'


class AnyAttributeValue(
    RootModel[
        Union[
            StringAttribute,
            DateAttribute,
            XHTMLAttribute,
            EnumerationAttribute,
            BooleanAttribute,
            RealAttribute,
            IntegerAttribute,
        ]
    ]
):
    root: Union[
        StringAttribute,
        DateAttribute,
        XHTMLAttribute,
        EnumerationAttribute,
        BooleanAttribute,
        RealAttribute,
        IntegerAttribute,
    ]
    """
    Union type accepting any ReqIF attribute or primitive value
    """
