# generated by datamodel-codegen:
#   filename:  defs/types/types.json
#   timestamp: 2025-12-10T22:32:46+00:00

from __future__ import annotations

from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class ReqifAttributeTypeDefinitions(RootModel[Any]):
    root: Any = Field(..., title='ReqIF Attribute Type Definitions')
    """
    Reusable attribute type definitions based on prostep ivip ReqIF Implementation Guide v1.8
    """


class BooleanAttribute(BaseModel):
    """
    AttributeDefinitionBoolean / AttributeValueBoolean - for true/false values
    """

    attributeType: Literal['BOOLEAN']
    """
    Attribute type in the specifications
    """
    selector: str
    """
    JSONPath pointer to the element from the parent node
    """
    literal: Optional[str] = None
    """
    Literal value for missing selector
    """
    longName: str
    """
    Long name for the attributes to reflect in ReqIf specification
    """
    type: Optional[str] = None
    """
    Datatype Name to be used in specification as {attributeType_type}
    """


class DateAttribute(BaseModel):
    """
    AttributeDefinitionDate / AttributeValueDate - for temporal values
    """

    attributeType: Literal['DATE']
    """
    Attribute type in the specifications
    """
    selector: str
    """
    JSONPath pointer to the element from the parent node
    """
    literal: Optional[str] = None
    """
    Literal value for missing selector
    """
    longName: str
    """
    Long name for the attributes to reflect in ReqIf specification
    """
    type: Optional[str] = None
    """
    Datatype Name to be used in specification as {attributeType_type}
    """


class EnumerationAttributeValue(BaseModel):
    """
    AttributeDefinitionEnumerationValue - for predefined choices
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    key: int
    value: str
    content: str


class EnumerationAttribute(BaseModel):
    """
    AttributeDefinitionEnumeration / AttributeValueEnumeration - for predefined choices
    """

    attributeType: Literal['ENUMERATION']
    """
    Attribute type in the specifications
    """
    values: list[EnumerationAttributeValue] = Field(..., min_length=1)
    selector: str
    """
    JSONPath pointer to the element from the parent node
    """
    literal: Optional[str] = None
    """
    Literal value for missing selector
    """
    longName: str
    """
    Long name for the attributes to reflect in ReqIf specification
    """
    type: Optional[str] = None
    """
    Datatype Name to be used in specification as {attributeType_type}
    """


class IntegerAttribute(BaseModel):
    """
    AttributeDefinitionInteger / AttributeValueInteger - for integer values
    """

    attributeType: Literal['INTEGER']
    """
    Attribute type in the specifications
    """
    min: Optional[Any] = None
    max: Optional[int] = None
    selector: str
    """
    JSONPath pointer to the element from the parent node
    """
    literal: Optional[str] = None
    """
    Literal value for missing selector
    """
    longName: str
    """
    Long name for the attributes to reflect in ReqIf specification
    """
    type: Optional[str] = None
    """
    Datatype Name to be used in specification as {attributeType_type}
    """


class RealAttribute(BaseModel):
    """
    AttributeDefinitionReal / AttributeValueReal - for numeric values with decimals
    """

    attributeType: Literal['REAL']
    """
    Attribute type in the specifications
    """
    accuracy: Optional[Any] = None
    """
    Number of decimal places
    """
    min: Optional[int] = None
    max: Optional[int] = None
    selector: str
    """
    JSONPath pointer to the element from the parent node
    """
    literal: Optional[str] = None
    """
    Literal value for missing selector
    """
    longName: str
    """
    Long name for the attributes to reflect in ReqIf specification
    """
    type: Optional[str] = None
    """
    Datatype Name to be used in specification as {attributeType_type}
    """


class StringAttribute(BaseModel):
    """
    AttributeDefinitionString / AttributeValueString - for text values
    """

    attributeType: Literal['STRING']
    """
    Attribute type in the specifications
    """
    maxLength: Optional[conint(ge=0)] = None
    selector: str
    """
    JSONPath pointer to the element from the parent node
    """
    literal: Optional[str] = None
    """
    Literal value for missing selector
    """
    longName: str
    """
    Long name for the attributes to reflect in ReqIf specification
    """
    type: Optional[str] = None
    """
    Datatype Name to be used in specification as {attributeType_type}
    """


class XHTMLAttribute(BaseModel):
    """
    AttributeDefinitionXHTML / AttributeValueXHTML - for formatted content
    """

    attributeType: Literal['XHTML']
    """
    Attribute type in the specifications
    """
    selector: str
    """
    JSONPath pointer to the element from the parent node
    """
    literal: Optional[str] = None
    """
    Literal value for missing selector
    """
    longName: str
    """
    Long name for the attributes to reflect in ReqIf specification
    """
    type: Optional[str] = None
    """
    Datatype Name to be used in specification as {attributeType_type}
    """


class AnyAttributeValue(
    RootModel[
        Union[
            StringAttribute,
            DateAttribute,
            XHTMLAttribute,
            EnumerationAttribute,
            BooleanAttribute,
            RealAttribute,
            IntegerAttribute,
        ]
    ]
):
    root: Union[
        StringAttribute,
        DateAttribute,
        XHTMLAttribute,
        EnumerationAttribute,
        BooleanAttribute,
        RealAttribute,
        IntegerAttribute,
    ]
    """
    Union type accepting any ReqIF attribute or primitive value
    """
