# generated by datamodel-codegen:
#   filename:  mapping_capella.json
#   timestamp: 2025-12-11T15:53:13+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .defs.requirement import Requirement
from .defs.requirement_doors import Requirement as Requirement_1
from .defs.specification import Specification as Specification_1
from .defs.specification_doors import Specification as Specification_2
from .defs.types import defaults


class Attributes(Specification_1, Specification_2):
    pass


class Specification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attributes: Attributes
    caption: defaults.Selector
    id: defaults.Selector
    selector: defaults.Selector
    type: str


class Attributes1(Requirement, Requirement_1):
    pass


class Variant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attributes: Attributes1
    children: Optional[defaults.Selector] = None
    match: defaults.Selector
    type: constr(min_length=1, max_length=100)


class Requirements(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: defaults.Selector
    variants: list[Variant] = Field(..., min_length=1)


class ReqifChoiceSchema(BaseModel):
    """
    JSON Schema where each field can match against any ReqIF attribute type using external definitions
    """

    config: defaults.Config
    specification: Specification
    requirements: Requirements
