# generated by datamodel-codegen:
#   filename:  defs/attributes/reqif.json
#   timestamp: 2025-12-11T15:53:13+00:00

from __future__ import annotations

from typing import Literal

from ...types.types import (
    BooleanAttribute,
    DateAttribute,
    EnumerationAttribute,
    IntegerAttribute,
    StringAttribute,
    XHTMLAttribute,
)


class AssociatedFiles(StringAttribute):
    longName: Literal['ReqIF.AssociatedFiles'] = 'ReqIF.AssociatedFiles'


class Category(EnumerationAttribute):
    longName: Literal['ReqIF.Category'] = 'ReqIF.Category'


class ChangeDescription(StringAttribute):
    longName: Literal['ReqIF.ChangeDescription'] = 'ReqIF.ChangeDescription'


class ChapterName(XHTMLAttribute):
    longName: Literal['ReqIF.ChapterName'] = 'ReqIF.ChapterName'


class ChapterNumber(StringAttribute):
    longName: Literal['ReqIF.ChapterNumber'] = 'ReqIF.ChapterNumber'


class Description(XHTMLAttribute):
    longName: Literal['ReqIF.Description'] = 'ReqIF.Description'


class FitCriteria(StringAttribute):
    longName: Literal['ReqIF.FitCriteria'] = 'ReqIF.FitCriteria'


class ForeignBaseline(StringAttribute):
    longName: Literal['ReqIF.ForeignBaseline'] = 'ReqIF.ForeignBaseline'


class ForeignCreatedBy(StringAttribute):
    longName: Literal['ReqIF.ForeignCreatedBy'] = 'ReqIF.ForeignCreatedBy'


class ForeignCreatedOn(DateAttribute):
    longName: Literal['ReqIF.ForeignCreatedOn'] = 'ReqIF.ForeignCreatedOn'


class ForeignCreatedThru(StringAttribute):
    longName: Literal['ReqIF.ForeignCreatedThru'] = 'ReqIF.ForeignCreatedThru'


class ForeignDeleted(BooleanAttribute):
    longName: Literal['ReqIF.ForeignDeleted'] = 'ReqIF.ForeignDeleted'


class ForeignID(IntegerAttribute):
    longName: Literal['ReqIF.ForeignID'] = 'ReqIF.ForeignID'


class ForeignModifiedBy(StringAttribute):
    longName: Literal['ReqIF.ForeignModifiedBy'] = 'ReqIF.ForeignModifiedBy'


class ForeignRevision(StringAttribute):
    longName: Literal['ReqIF.ForeignRevision'] = 'ReqIF.ForeignRevision'


class ForeignState(StringAttribute):
    longName: Literal['ReqIF.ForeignState'] = 'ReqIF.ForeignState'


class Name(XHTMLAttribute):
    longName: Literal['ReqIF.Name'] = 'ReqIF.Name'


class Prefix(StringAttribute):
    longName: Literal['ReqIF.Prefix'] = 'ReqIF.Prefix'


class Project(StringAttribute):
    longName: Literal['ReqIF.Project'] = 'ReqIF.Project'


class Text(XHTMLAttribute):
    longName: Literal['ReqIF.Text'] = 'ReqIF.Text'
