# generated by datamodel-codegen:
#   filename:  mapping.json
#   timestamp: 2025-12-10T22:32:46+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .defs import requirement
from .defs import specification as specification_1
from .defs.types import defaults


class Specification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attributes: specification_1.Specification
    caption: defaults.Selector
    id: defaults.Selector
    selector: defaults.Selector
    requirements: defaults.Selector
    type: str


class Variant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attributes: requirement.Requirement
    children: Optional[defaults.Selector] = None
    match: defaults.Selector
    type: constr(min_length=1, max_length=100)


class Requirements(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: defaults.Selector
    variants: list[Variant] = Field(..., min_length=1)


class ReqifChoiceSchema(BaseModel):
    """
    JSON Schema where each field can match against any ReqIF attribute type using external definitions
    """

    config: defaults.Config
    specification: Specification
    requirements: Requirements
